export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'; 
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const INSERT_CUSTOMER = 'INSERT_CUSTOMER';
export const INSERT_CUSTOMER_IN_LIST = 'INSERT_CUSTOMER_IN_LIST';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';